# Generated by Django 4.2.4 on 2023-08-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
